coinbase:
  pricing_url: "https://api.coindesk.com/v1/bpi/currentprice.json"
  supported_ccy: ['USD', 'GBP', 'EUR']

cache:
  refresh_time: 1

log:
  format: "%(asctime)s | %(levelname)s | %(filename)s:%(lineno)s | %(process)d >>> %(message)s"
  level: 'DEBUG'
